### ISSUE TITLE
Blinds. What i am doing wrong?

### ISSUE THREAD

**Issue by h3ad** [hplato/homebridge-httpmulti#13]
I added 3 accessories to my homebridge.
Light and switch works well, but blind always report me error
[11/25/2016, 11:49:50 PM] [Room Blinds] up=undefined down=undefined method=undefined
/usr/lib/node_modules/homebridge-httpmulti/index.js:501
      this.log("Error getting state (status code %s): %s", response.StatusCode, err);

Here is my config file

,{
    "accessory": "HttpMulti",
    "name": "Room Blinds",
    "on_url": "http://myIP/send?deviceMac=MAC&codeId=95",
    "off_url": "http://myIP/send?deviceMac=MAC4&codeId=96",
    "deviceType": "blinds",
    },{
    "accessory": "HttpMulti",
    "name": "relay",
    "on_url": "http://myIP/send?deviceMac=MAC&codeId=95",
    "off_url": "http://myIP/send?deviceMac=MAC&codeId=96",
    "deviceType": "switch"
    },{
    "accessory": "HttpMulti",
    "name": "a light",
    "on_url": "http://myIP/send?deviceMac=MAC&codeId=95",
    "off_url": "http://myIP/send?deviceMac=MAC&codeId=96",
    "brightness_url": "http://myIP/send?deviceMac=MAC&codeId=96",
    "deviceType": "light"
    }

**Comment by hplato** [comment]
Blinds need to be up_url and down_url. Give that a try.

**Comment by h3ad** [comment]
Thanks it's work =)
