### ISSUE TITLE
Fan device configuration

### ISSUE THREAD

**Issue by Aaimek** [hplato/homebridge-httpmulti#16]
Hi!
So I was trying to add my fan to Homebridge using your plugin, the problem is, I didn't find any clear description of how to configure it. So I tried multiple things like this:

`   {
        "accessory": "HttpMulti",
        "name": "Fan",
        "deviceType": "fan",
        "model": "myFan",
        "on_url": "http://myFanIp/on",
        "off_url": "http://myFanIp/off",
        "status_url": "http://myFanIp/powerPercent",
        "speed_url": "http://myFanIp/set/%VALUE%"
   }`

I tried it without the `"speed_url"`, without the `"status_url"` too, but nothing worked and Homebridge kept bugging. Note that `/powerPercent` return  a value between 0 and 100. And that `/set/%VALUE%` must be a value between 0 and 100. Please help me!

**Comment by hplato** [comment]
It looks like you've done everything right. Here's what I have which is working for me:

    {
    "accessory": "HttpMulti",
    "name": "Room Fan",
    "on_url": "http://IP/SET?select_item=$room_fan&select_state=on",
    "off_url": "http://IP/SET?select_item=$room_fan&select_state=off",
    "speed_url": "http://IP/SET?select_item=$room_fan&select_state=%VALUE%",
    "status_url": "http://IP/get_status%28room_fan%29",
    "deviceType": "fan"
    },

The get_status will return a value between 0 and 100.

**Comment by Aaimek** [comment]
I've tried it in this order and it works, awesome! thanks!

**Comment by hplato** [comment]
Thanks for the follow-up. Weird, since the order of the elements shouldn't really matter, but glad that it's working for you.
