### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by TRIROG** [hplato/homebridge-httpmulti#3]
Please provide the installation instructions.
Thanks!

**Comment by hplato** [comment]
Shouldn't be too bad.

In my case, my accessories are installed in /usr/lib/node_modules. CD into that directory

$ git clone https://github.com/hplato/homebridge-httpmulti.git

This should create a homebridge-httpmulti directory.

Then create your config.json file (mine is in /root/.homebridge/)

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:11:3D:C3:DE:35",
		"port": 51826,
		"pin": "123-45-678"
	},
	"description": "Somthing",

	"accessories": [
		{
		"accessory": "HttpMulti",
		"name": "A Fan",
		"on_url": "http://ip/fan&select_state=on",
		"off_url": "http://ip/fan&select_state=off",
		"deviceType": "fan"
		},
		{
		"accessory": "HttpMulti",
		"name": "relay",
		"on_url": "http://...",
		"off_url": "http://...",
		"deviceType": "switch"
		},
		{
		"accessory": "HttpMulti",
		"name": "a light",
		"on_url": "http://...",
		"off_url": "http://...",
		"brightness_url": "http://...",
		"deviceType": "light"
		},
		{
		"accessory": "HttpMulti",
		"name": "Door Lock",
		"lock_url": "http://...",
		"unlock_url": "http://...",
		"deviceType": "lock"
		},
		{
		"accessory": "HttpMulti",
		"name": "Garage Door",
		"open_url": "http://...",
		"close_url": "http://...",
		"deviceType": "garagedoor"
		},
		{
		"accessory": "HttpMulti",
		"name": "Room Blinds",
		"on_url": "http://...",
		"off_url": "http://...",
		"deviceType": "blinds"
		},
		{
		"accessory": "HttpMulti",
		"name": "A Thermostat",
		"setpoint_url": "http://...",
		"deviceType": "thermostat"
		}
	]
}

**Comment by Zorgonaute84** [comment]
Very great pluggin, thank you !

But I've got 3 question for you.

First, what is the name of the variable used for the brightness ? I tried %b as in the Http plugin, but it doesn't work.

Second question, I created blinds accessory without success. The accessories are created, and available in Insteon+ but when I asked Siri about blinds, he told me that I havn't blinds.

Third question, is it normal that "switch" accessories are considered as light in Siri. If I told to turn on all my light, it turn on my switch too... I should remember that it wasn't the case with Http.

Thanks for your help

**Comment by hplato** [comment]
Here’s an example of a brightness URL that works for me:

	"brightness_url": "http://10.0.0.1:80/SET;none?select_item=$back_deck_light&select_state=%VALUE%”,

2. What version of IOS are you using. I seem to recall that v9 is needed for blinds. I use this successfully with IOS 9.3

		"accessory": "HttpMulti",
		"name": “Main Blinds",
		"on_url": "http://10.0.0.2:80/SET;none?select_item=$b1&select_state=on",
		"off_url": "http://10.0.0.3:80/SET;none?select_item=$b2&select_state=off",
		"deviceType": “blinds"

3.  I think so. I’ve never tried turning on all the lights...

**Comment by Zorgonaute84** [comment]
Thanks for the brightness URL, I'll try.

About blinds, in Insteon the accessory look very strange because it havn't any button. 
For exemple a switch have an ON and OFF button in Insteon, a light have ON, OFF and a slide, a garage door have 2 icons to open and close the door. But about the blinds, there is nothing...

My iOS version is 9.3.2

**Comment by tumekee** [comment]
is it possible to use/add a status_url ( or similar ) on the  "garagedoor" ? then I can set up a read switch connected to an Arduino board which will show if its open / closed / obstruction ?

**Comment by hplato** [comment]
There is probably a way, but it's not clear to me how that connects in.

**Comment by phpfs** [comment]
Any Updates on blinds for IOS10?

Thanks :)

**Comment by hplato** [comment]
I haven't looked at this yet. Hopefully over the next few weeks.

**Comment by nawaidrana** [comment]
I am always getting this error, with your new httpmulti or with legacy httpmulti:

Garage Door Obstruction Read:
Garage Door - current door state Read

And the message comes up as soon as I open the Home app on iphone, with all status showing as updating.

When I use Insteon accessory (using Insteon.js) I can open my garage but I dont like how I have to say "turn garage on" rather than turn garage open ... 

Any help will be appreciated.

**Comment by nawaidrana** [comment]
And BTW, when I type in that http directly in my browser, my garage opens (same http for open and close): 

http://user:password@10.0.1.12:25105/3?0262347Y4D0F12ff=I=3

**Comment by hplato** [comment]
I'm going to have to redo the accessory since it looks like a few things have changed. No big deal, but will take some time. Have blinds working with IOS10

**Comment by hplato** [comment]
And now lightbulbs... Probably in a few days this will be updated.

**Comment by hplato** [comment]
OK, the v2 of this accessory seems to mostly work. I can control all the objects with either the IOS10 home app or Siri. More work needs to be done for status, but for now this should be a decent update for anyone using it.

**Comment by TRIROG** [comment]
Are the config.json examples posted here still valid in v2? I cant see to be able to get this plugin to work?

**Comment by phpfs** [comment]
The error seems to be the response of your device.

As the StackTrace says, it is expecting a key named StatusCode.

Have a look at index.js, line 501 and find the accessory type it is about. Also check your statusurl you listed in config.json!

Greetings phpfs

**Comment by hplato** [comment]
Well, its not the neatest, but I copied up my config.json to the wiki that has a working set of parameters for each httpmulti type.

**Comment by TRIROG** [comment]
@hplato  Great.! This will surely help ... Where can i check out the accepted inputs form the server, so i can modify my openhab outputs?

**Comment by hplato** [comment]
Probably the simplest way is to look at the perl code I did for Misterhouse. 

https://github.com/hplato/misterhouse/blob/homebridge/code/common/homebridge.pl <https://github.com/hplato/misterhouse/blob/homebridge/code/common/homebridge.pl>

The subrotine hb_status shows how I parse object states and what value I return to the httpmulti accessory

**Comment by TRIROG** [comment]
So after messing around a bit i figured it out:

My config was wrong i.e. based on the config example from april 13th. :\ i was using   
```
    "open_url": "http://...",
    "close_url": "http://...",
```

as opposed to:
    "up_url": "http://...",
    "down_url": "http://...",
